---
- name: Deploy matching cert/key to hosts
  hosts: all
  gather_facts: true
  become: true
  vars:
    tls_cert_path: /etc/pki/tls/certs/server.pem
    tls_key_path: /etc/pki/tls/private/server.key

  pre_tasks:
    - name: Sanity check - cert_map exists (from workflow artifacts)
      assert:
        that:
          - cert_map is defined
          - cert_map | length > 0
        fail_msg: >
          cert_map is not defined. Ensure the previous workflow job publishes it
          using set_stats (data: { cert_map: ... }).

    - name: Determine match name (fqdn -> inventory fallback)
      set_fact:
        match_name: "{{ ansible_fqdn | default(inventory_hostname) }}"

    - name: Fail if no cert matches this host
      fail:
        msg: "No certificate in bundle matches {{ match_name }}"
      when: cert_map[match_name] is not defined

  tasks:
    - name: Copy cert
      copy:
        src: "{{ cert_map[match_name].cert }}"
        dest: "{{ tls_cert_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Copy key
      copy:
        src: "{{ cert_map[match_name].key }}"
        dest: "{{ tls_key_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Reload httpd (ignore if not present)
      service:
        name: httpd
        state: reloaded
      ignore_errors: true
