---
- name: Rotate apache certs using cert_map from workflow artifacts
  hosts: all
  gather_facts: true
  become: true
  vars:
    tls_cert_path: /etc/pki/tls/certs/server.pem
    tls_key_path: /etc/pki/tls/private/server.key
  tasks:
    - name: Sanity check - cert_map exists in workflow artifacts
      assert:
        that:
          - ansible_stats is defined
          - ansible_stats.data is defined
          - ansible_stats.data.cert_map is defined
        fail_msg: >
          cert_map was not found in workflow artifacts. Ensure the previous workflow node
          publishes it using set_stats and that "Pass artifacts" is enabled on the node.

    - name: Determine match name (fqdn -> inventory fallback)
      set_fact:
        match_name: "{{ ansible_fqdn | default(inventory_hostname) }}"

    - name: Fail if no cert matches this host
      fail:
        msg: "No certificate in bundle matches {{ match_name }}"
      when: ansible_stats.data.cert_map[match_name] is not defined

    - name: Copy cert
      copy:
        src: "{{ ansible_stats.data.cert_map[match_name].cert }}"
        dest: "{{ tls_cert_path }}"
        owner: root
        group: root
        mode: "0644"

    - name: Copy key
      copy:
        src: "{{ ansible_stats.data.cert_map[match_name].key }}"
        dest: "{{ tls_key_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Reload httpd (ignore if not present)
      service:
        name: httpd
        state: reloaded
      ignore_errors: true
